set(CPACK_PACKAGE_NAME "lib${PROJECT_NAME}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Siemens filesystem library")
set(CPACK_PACKAGE_VENDOR "Siemens Mobile Hackers")

if(DEV_BUILD)
    string(APPEND CPACK_PACKAGE_DESCRIPTION_SUMMARY ". Unstable version.")
endif()

set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_SOURCE_DIR}/_packages_deb")

set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")

set(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE ${DIST_ARCH})

set(CPACK_DEBIAN_PACKAGE_DEPENDS "${DIST_DEPS}")

set(CPACK_PACKAGE_CONTACT "roman@serov.co")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Roman Serov")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/siemens-mobile-hacks")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
set(CPACK_DEBIAN_FILE_NAME "${CPACK_PACKAGE_NAME}-${DIST_NAME}-v${PACKAGE_VERSION}_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}.deb")
set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)
set(CPACK_DEB_COMPONENT_INSTALL YES)

include(CPack)
